# Generated by Django 4.2.9 on 2026-10-02 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0002_alter_warning_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('interval_days', models.PositiveIntegerField(verbose_name='复核周期(天)')),
                ('initial_grace_days', models.PositiveIntegerField(default=0, verbose_name='首次复核宽限(天)')),
                ('abnormal_interval_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='异常后复核周期(天)')),
                ('check_items', models.JSONField(default=list, verbose_name='检查项目')),
                ('remark', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '生效中'), ('deprecated', '已停用')], default='draft', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_rules', to='warehouse.category', verbose_name='适用品类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_review_rules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '复核规则',
                'verbose_name_plural': '复核规则',
                'db_table': 'insp_review_rule',
                'ordering': ['category_id', '-version', '-id'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='复核序号')),
                ('rule_snapshot', models.JSONField(default=dict, verbose_name='规则快照')),
                ('due_date', models.DateField(verbose_name='应复核期限')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='warehouse.goods', verbose_name='物资')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='inspections.reviewrule', verbose_name='适用规则版本')),
            ],
            options={
                'verbose_name': '复核待办',
                'verbose_name_plural': '复核待办',
                'db_table': 'insp_review_task',
                'ordering': ['due_date', '-id'],
                'unique_together': {('goods', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='ReviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_snapshot', models.JSONField(default=dict, verbose_name='规则快照')),
                ('conclusion', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], default='normal', max_length=20, verbose_name='复核结论')),
                ('abnormal_items', models.JSONField(default=list, verbose_name='异常项')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='下次复核期限')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_results', to='warehouse.goods', verbose_name='物资')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_results', to=settings.AUTH_USER_MODEL, verbose_name='检查人')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='inspections.reviewrule', verbose_name='采用规则版本')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='inspections.reviewtask', verbose_name='复核待办')),
            ],
            options={
                'verbose_name': '复核结果',
                'verbose_name_plural': '复核结果',
                'db_table': 'insp_review_result',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('stock_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_approvals', to='warehouse.stockout', verbose_name='出库记录')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_approvals', to='inspections.reviewtask', verbose_name='逾期复核待办')),
            ],
            options={
                'verbose_name': '逾期放行审批',
                'verbose_name_plural': '逾期放行审批',
                'db_table': 'insp_release_approval',
                'ordering': ['-created_at'],
                'unique_together': {('stock_out', 'task')},
            },
        ),
    ]
