# Generated by Django 4.2.9 on 2026-10-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='type',
            field=models.CharField(choices=[('low_stock', '库存不足'), ('expiring', '即将过期'), ('expired', '已过期'), ('review_overdue', '周期复核逾期')], max_length=20, verbose_name='预警类型'),
        ),
    ]
