# Generated by Django 4.2.9 on 2026-10-02 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('interval_days', models.PositiveIntegerField(verbose_name='复核周期（天）')),
                ('check_items', models.JSONField(default=list, verbose_name='检查项目')),
                ('overdue_grace_days', models.PositiveIntegerField(default=0, verbose_name='逾期宽限天数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('deprecated', '已作废')], default='draft', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('deprecated_at', models.DateTimeField(blank=True, null=True, verbose_name='作废时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_rules', to='warehouse.category', verbose_name='适用品类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_review_rules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '复核规则版本',
                'verbose_name_plural': '复核规则版本',
                'db_table': 'wh_review_rule_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(default='stock_out', max_length=30, verbose_name='审批类型'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='extra_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_stock_outs', to='warehouse.approval', verbose_name='逾期复核额外审批'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='type',
            field=models.CharField(choices=[('low_stock', '库存不足'), ('expiring', '即将过期'), ('expired', '已过期'), ('review_overdue', '复核逾期')], max_length=20, verbose_name='预警类型'),
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_date', models.DateField(verbose_name='基准日期（入库日期或上次结论日期）')),
                ('due_date', models.DateField(verbose_name='复核期限')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='warehouse.goods', verbose_name='物资')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_tasks', to='warehouse.reviewruleversion', verbose_name='依据规则版本')),
            ],
            options={
                'verbose_name': '复核待办',
                'verbose_name_plural': '复核待办',
                'db_table': 'wh_review_task',
                'ordering': ['due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_snapshot', models.JSONField(verbose_name='采用规则快照')),
                ('conclusion', models.CharField(choices=[('qualified', '合格'), ('abnormal', '异常')], max_length=20, verbose_name='复核结论')),
                ('abnormal_items', models.JSONField(default=list, verbose_name='异常项')),
                ('next_due_date', models.DateField(verbose_name='下一次复核期限')),
                ('review_date', models.DateField(verbose_name='复核日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='warehouse.goods', verbose_name='物资')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_records', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_records', to='warehouse.reviewruleversion', verbose_name='采用的规则版本')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='warehouse.reviewtask', verbose_name='来源待办')),
            ],
            options={
                'verbose_name': '复核结果',
                'verbose_name_plural': '复核结果',
                'db_table': 'wh_review_record',
                'ordering': ['-review_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='reviewtask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('goods',), name='uniq_pending_review_task_per_goods'),
        ),
        migrations.AddConstraint(
            model_name='reviewruleversion',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'version'), name='uniq_review_rule_category_version'),
        ),
        migrations.AddConstraint(
            model_name='reviewruleversion',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('version',), name='uniq_review_rule_global_version'),
        ),
    ]
