# Generated by Django 4.2.9 on 2026-10-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_reviewruleversion_approval_approval_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('stock_out', '出库审批'), ('overdue_review', '复核逾期额外审批')], default='stock_out', max_length=30, verbose_name='审批类型'),
        ),
    ]
